name = "fastmail20251007"
# name = "mail-exhibit"
main = "src/server.js"
compatibility_date = "2024-01-01"

# D1 数据库绑定
[[d1_databases]]
binding = "TEMP_MAIL_DB"
database_name = "maill_free_db_20251007" #你的d1数据库名称
database_id = "a6aa5d2a-17c4-468b-93bd-d354a5631883" # 你的database_id

# 环境变量
[vars]


# 静态资源目录（Workers + Assets）
[assets]
directory = "public"
# 显式指定绑定名，确保在 Worker 中通过 env.ASSETS 可用
binding = "ASSETS"


# R2 存储桶绑定（用于保存完整 EML 内容）
[[r2_buckets]]
binding = "MAIL_EML"
bucket_name = "mail-eml-20251007"

# wrangler.toml (wrangler v3.88.0^) 日志服务
# [observability.logs]
# enabled = true



